name: Build and Upload Release Assets

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Go environment
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true

      # Build binaries for multiple architectures
      - name: Build binaries
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=arm64 go build -o dist/tinoagent-linux-arm64 ./cmd/agent.go
          GOOS=linux GOARCH=arm go build -o dist/tinoagent-linux-arm ./cmd/agent.go
          GOOS=linux GOARCH=amd64 go build -o dist/tinoagent-linux-amd64 ./cmd/agent.go
          GOOS=linux GOARCH=386 go build -o dist/tinoagent-linux-amd ./cmd/agent.go

      # Verify built binaries
      - name: Verify binaries
        run: ls -lh dist/

      # Upload all binaries to GitHub Release
      - name: Upload binaries
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/tinoagent-linux-arm64
          asset_name: tinoagent-linux-arm64
          asset_content_type: application/octet-stream

      - name: Upload binaries
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/tinoagent-linux-arm
          asset_name: tinoagent-linux-arm
          asset_content_type: application/octet-stream

      - name: Upload binaries
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/tinoagent-linux-amd64
          asset_name: tinoagent-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload binaries
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/tinoagent-linux-amd
          asset_name: tinoagent-linux-amd
          asset_content_type: application/octet-stream
