name: Build and Upload Release Assets

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build binaries
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/tinoagent-linux-amd64 ./cmd/agent.go
          GOOS=linux GOARCH=arm64 go build -o dist/tinoagent-linux-arm64 ./cmd/agent.go
          GOOS=linux GOARCH=386 go build -o dist/tinoagent-linux-amd ./cmd/agent.go
          GOOS=linux GOARCH=arm go build -o dist/tinoagent-linux-arm ./cmd/agent.go

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/tinoagent-linux-arm64
            dist/tinoagent-linux-arm
            dist/tinoagent-linux-amd64
            dist/tinoagent-linux-amd
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
